[workspace]
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["https://prefix.dev/conda-forge", "anybody/label/rc82"]
name = "strength-model"
platforms = ["win-64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
process_ams = "python run.py"

[dependencies]
anypytools = ">=1.20.4"
python="3.13.*"
polars = ">=1.34.0,<2"
pyarrow = ">=21.0.0,<22"
pandas = ">=2.3.3,<3"
plotly = ">=6.4.0,<7"
typer = ">=0.20.0,<0.21"

[target.win-64.dependencies]
anybodycon = ">=8.2.0beta9,<9"


[feature.marimo.tasks]
convert = "marimo edit convert-matlab-data/convert-matlab-data.py"
start = "marimo edit visualize.py"

[feature.marimo.dependencies]
polars = "*"
altair = "*"
sqlglot = "*"
openai = "*"
ruff = "*"
nbformat = "*"
python-lsp-server = "*"
python-lsp-ruff = "*"
mcp = "*"
python_version = "*"
scipy = "*"
click = "*"
jedi = "*"
markdown = "*"
pymdown-extensions = "*"
pygments = "*"
tomlkit = "*"
pyyaml = "*"
uvicorn = "*"
starlette = "*"
loro = "*"
websockets = "*"
docutils = "*"
psutil = "*"
narwhals = "*"
packaging = "*"
msgspec = "*"
pytest = "*"
marimo = "*"
python-calamine = "*"
fastexcel = "*"
pyarrow = "*"
uv = "*"
plotly = "*"
google-genai = ">=1.60.0,<2"

[feature.marimo.pypi-dependencies]
# google-generativeai = ">=0.8.5"
# google-genai = ">=1.52.0"

[environments]
marimo = {features = ["marimo"], no-default-feature = true}
