[workspace]
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["https://prefix.dev/conda-forge", "anybody/label/rc82"]
name = "strength-model"
platforms = ["win-64", "linux-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
start = "python run.py"

[dependencies]
# anypytools = {path="D:/repos/AnyPyTools"}
anypytools = ">=1.19.2"
python="3.13.*"
polars = ">=1.34.0,<2"
pyarrow = ">=21.0.0,<22"
pandas = ">=2.3.3,<3"
plotly = ">=6.4.0,<7"
typer = ">=0.20.0,<0.21"

[target.win-64.dependencies]
anybodycon = ">=8.2.0beta7,<9"


[feature.marimo.tasks]
convert = "marimo edit convert-matlab-data/convert-matlab-data.py"
marimo = "marimo"

[feature.marimo.dependencies]
polars = ">=1.35.1,<2"
altair = ">=5.5.0,<6"
sqlglot = ">=27.29.0,<28"
openai = ">=2.7.1,<3"
ruff = ">=0.14.4,<0.15"
nbformat = ">=5.10.4,<6"
python-lsp-server = ">=1.13.1,<2"
python-lsp-ruff = ">=2.3.0,<3"
mcp = ">=1.20.0,<2"
python_version = ">=0.0.2,<0.0.3"
scipy = ">=1.16.3,<2"
click = ">=8.3.0,<9"
jedi = ">=0.19.2,<0.20"
markdown = ">=3.10,<4"
pymdown-extensions = ">=10.16.1,<11"
pygments = ">=2.19.2,<3"
tomlkit = ">=0.13.3,<0.14"
pyyaml = ">=6.0.3,<7"
uvicorn = ">=0.38.0,<0.39"
starlette = ">=0.50.0,<0.51"
loro = ">=1.8.2,<2"
websockets = ">=15.0.1,<16"
docutils = ">=0.22.3,<0.23"
psutil = ">=7.1.3,<8"
narwhals = ">=2.10.2,<3"
packaging = ">=25.0,<26"
msgspec = ">=0.19.0,<0.20"
pytest = ">=8.4.2,<9"
marimo = ">=0.17.7,<0.18"
python-calamine = ">=0.5.3,<0.6"
fastexcel = ">=0.16.0,<0.17"
pyarrow = ">=22.0.0,<23"
uv = ">=0.9.7,<0.10"
plotly = ">=6.4.0,<7"

[feature.marimo.pypi-dependencies]
google-generativeai = ">=0.8.5, <0.9"
google-genai = ">=1.49.0, <2"

[environments]
marimo = {features = ["marimo"], no-default-feature = true}
