[workspace]
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["https://prefix.dev/conda-forge", "anybody/label/rc82"]
name = "strength-model"
platforms = ["win-64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
start = "python run.py"

[dependencies]
anybodycon = ">=8.2.0beta7,<9"
anypytools = {path="D:/repos/AnyPyTools"}
python="3.14.*"
polars = ">=1.34.0,<2"
pyarrow = ">=21.0.0,<22"

[feature.convert.tasks]
convert = "marimo edit convert-matlab-data/convert-matlab-data.py"

[feature.convert.dependencies]
polars = ">=1.33.1,<2"
altair = ">=5.5.0,<6"
sqlglot = ">=27.16.3,<28"
openai = ">=1.108.1,<2"
ruff = ">=0.13.1,<0.14"
nbformat = ">=5.10.4,<6"
python-lsp-server = ">=1.13.1,<2"
python-lsp-ruff = ">=2.2.2,<3"
mcp = ">=1.14.0,<2"
python_version = ">=0.0.2,<0.0.3"
scipy = ">=1.16.2,<2"
click = ">=8.0,<9"
jedi = ">=0.18.0"
markdown = ">=3.6,<4"
pymdown-extensions = ">=10.15,<11"
pygments = ">=2.13,<3"
tomlkit = ">=0.12.0"
pyyaml = ">=6.0"
uvicorn = "==0.35.0"
starlette = ">=0.35.0,!=0.36.0"
loro = ">=1.5.0"
websockets = ">=14.2.0"
docutils = ">=0.16.0"
psutil = ">=5.0"
narwhals = ">=1.34.1"
packaging = "*"
msgspec = ">=0.19.0"
pytest = ">=8.4.2,<9"
marimo = "*"
python-calamine = ">=0.5.3,<0.6"
fastexcel = ">=0.16.0,<0.17"
pyarrow = ">=21.0.0,<22"

[environments]
convert = {features = ["convert"], no-default-feature = true}
